apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: redis-operator

resources:
  - databases.spotahome.com_redisfailovers.yaml
  - deployment.yaml
