apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover-with-authv2
spec:
  sentinel:
    replicas: 3
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
  redis:
    replicas: 3
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi
  authV2:
    enabled: true
    users:
      default:
        passwords:
        - value: default
        acl:
          value: "+@all"
      test:
        passwords:
          - valueFrom:
              name: test
              key: password
        acl: 
          value: ""
      admin:
        passwords:
          - value: "admintest"
        acl: 
          value: " +@all"

---
apiVersion: v1
data:
  #testpassword
  password: |-
    dGVzdHBhc3N3b3Jk
kind: Secret
metadata:
  name: test
type: Opaque