annotations:
  category: Redis Operator
appVersion: 1.2.0
apiVersion: v1
description: A Helm chart for the Spotahome Redis Operator
name: redis-operator
version: 3.2.1
home: https://github.com/spotahome/redis-operator
keywords:
  - "golang"
  - "operator"
  - "cluster"
sources:
  - https://github.com/spotahome/redis-operator
